name: 'Check Deadline'
description: 'Checks an assignment deadline and determines a late penalty if needed.'
inputs:
  assignment_name:
    description: 'Assignment name'
    required: true
  starting_points:
    description: 'Earned points before late penalties'
    default: '100'
    required: true
  submitted_date:
    description: 'Date submitted (ISO format)'
    required: false
  extension_hours:
    description: 'Amount of extension granted (in hours)'
    default: '0'
    required: false
outputs:
  assignment_name:
    description: 'Name of assignment'
  submitted_iso:
    description: 'Submitted (in ISO format)'
  submitted_text:
    description: 'Submitted (in readable text)'
  deadline_iso:
    description: 'Deadline (in ISO format)'
  deadline_text:
    description: 'Deadline (in readable text)'
  late_interval:
    description: 'Late interval (in hours, 0 if not late)'
  late_multiplier:
    description: 'Late penalty multiplier'
  late_percent:
    description: 'Late penalty (in percent)'
  late_points:
    description: 'Late penalty (in points)'
  grade_starting:
    description: 'Earned points before late penalties'
  grade_possible:
    description: 'Total points possible'
  grade_points:
    description: 'Late grade (in points)'
  grade_percent:
    description: 'Late grade (in percent)'
  results_name:
    description: 'Name of results artifact'
  results_json:
    description: 'Name of results JSON file'
  workflow_run:
    description: 'Workflow run that generated these results'
runs:
  using: 'node16'
  main: 'index.js'
